# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b8c815a8b9d6a818378f0f98a18931ba486240e75b83d3b16f64a04abe7988f57032f950aecc60e35b9490f1fffe368d64b2c225af0978db92c1b4f236f5780

test:
  secret_key_base: eac56193959aa2abdc8fe81b373776e1be970694b7e8adac9b45265ca925cdd7dea91733d58b1e0bd1983209d92b6416434eb652bb0bf330477c4adcff1d4c10

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
